doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
#            options:
#                username: '%env(resolve:MONGODB_USER)%'
#                password: '%env(resolve:MONGODB_PASSWD)%'
#                ssl: false
#    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App\Rezig:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/config/doctrine/mongodb'
                    prefix: 'App\Rezig\Scores\Model'
#                    alias: App

#                App:
#                    is_bundle: false
#                    type: annotation
#                    dir: '%kernel.project_dir%/src/Document'
#                    prefix: 'App\Document'
#                    alias: App
