version: "3"

services:
  cli:
    build:
      context: ./docker
    volumes:
      - .:/volume
    stdin_open: true
    tty: true
    ports:
    - 8000:8000

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo_data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: topsecred
#      MONGO_INITDB_DATABASE: teeest

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: topsecred
