# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    private_jacek.protocol: "https"
    private_jacek.domain: "private-b5236a-jacek10.apiary-mock.com"
    private_jacek.scores_uri: "results/games"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Rezig\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Rezig\Scores\UI\Controller\:
        resource: '../src/Scores/UI/Controller/*'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Rezig\Scores\UI\Controller\ResultsController:
        tags: [controller.service_arguments]
        bind:
            $dataProvider: '@App\Rezig\Scores\DataProvider\LocalGameResultsDataProvider'
            $converter: '@App\Rezig\Scores\Converter\Converter'

    App\Rezig\Scores\DataProvider\LocalGameResultsDataProvider:
        $externalGameResultsDataProvider: '@App\Rezig\Scores\DataProvider\ExternalGameResultsDataProvider'
        $resultsRepository: '@App\Rezig\Scores\Infrastructure\Storage\Mongo\ResultsRepository'
        $sorter: '@App\Rezig\Scores\DataProvider\Sorter\ObjectSorter'

    App\Rezig\Scores\DataProvider\ExternalGameResultsDataProvider:
        $sorter: '@App\Rezig\Scores\DataProvider\Sorter\Sorter'

    App\Rezig\Scores\Infrastructure\Http\Parser\ParserContext:
        factory: ['@App\Rezig\Scores\ContainerFactory\ParserContextFactory', 'create']

    App\Rezig\Scores\Infrastructure\Http\Api\PrivateJacekApiClient:
        arguments:
            $protocol: '%private_jacek.protocol%'
            $domain: '%private_jacek.domain%'
            $scoresUri: '%private_jacek.scores_uri%'
            $httpClientFactory: '@App\Rezig\Scores\ContainerFactory\HttpClientFactory'
            $parserContext: '@App\Rezig\Scores\Infrastructure\Http\Parser\ParserContext'
